version: '3.3'
services: 
  db:
    image: mysql:8.0
    container_name: db
    env_file: .env
    environment: 
      - MYSQL_DATABASE=wordpress
    volumes: 
      - db-data:/var/lib/mysql
    networks: 
      - main-network
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
  wordpress:
    image: wordpress:5.3.2-php7.2-apache
    container_name: wordpress
    env_file: .env
    environment: 
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=1
    volumes: 
      - wordpress-data:/var/www/html
    networks: 
      - main-network
    ports: 
      - 80:80
    restart: always
volumes: 
  db-data:
  wordpress-data:
networks: 
  main-network:
    driver: bridge